version: '2'

services:
    santa_game:
        build: .
        cap_add:
            - SYS_PTRACE
        security_opt:
          - seccomp:unconfined
          - apparmor:unconfined
        privileged: true
        ports:
            - "31337:31337"
