version: '2'

services:
    babyseccomp:
        build: .
        cap_add:
            - SYS_PTRACE
        security_opt:
          - seccomp:unconfined
          - apparmor:unconfined
        privileged: true
        ports:
            - "23457:3000"
